class_name Quests
## Every quest, WoW style: a giver with a reason, an objective you can read in one line, a little
## flavour, and rewards (experience, money, an item or a choice of items, reputation).
## Text for Ashvale Province is from docs/QUESTS.md (part B), which is the model for every zone.
##
## objective kinds: talk {npc} · kill {mon, n} · collect {item, n, from: [monster kinds], chance} ·
##                  explore {at, r, name} · gather {item, n} (things to pick up off the ground)
## money is in copper (100 copper = 1 silver).

const LIST := {
	# ================================================================ Hub 1 — Ashvale town
	"word_with_elder": {"title": "A Word with the Elder", "giver": "rowan", "ender": "bess", "level": 1, "min": 1, "chain": "Welcome",
		"offer": "Welcome to Ashvale. You've the look of someone who wants to be useful. Good — we're short of those. Go and see Bess at the inn before you do anything else; she feeds everyone who lifts a sword for this town, and she'll want to know your name.",
		"goal": "Speak to Bess at the inn.",
		"done": "So you're the new one. Rowan sends me all the strays. Sit, eat — then we'll talk about rats.",
		"obj": [{"kind": "talk", "npc": "bess"}], "xp": 60, "items": ["warm_meal"], "rep": 25},
	"pests_in_fields": {"title": "Pests in the Fields", "giver": "bess", "level": 1, "min": 1, "after": ["word_with_elder"],
		"offer": "Rats in the grain again. Big ones. If I feed you, you kill rats — that's the deal in this inn. They're in the fields behind the well; mind the hens, they're not the problem.",
		"goal": "Kill 8 Field Rats in the fields behind the well.",
		"progress": "Still rats in my grain, love.", "done": "Eight. I counted. You'll do.",
		"obj": [{"kind": "kill", "mon": "field_rat", "n": 8}], "xp": 90, "money": 300, "rep": 25, "where": "the fields west of the square, behind the well"},
	"hen_feathers": {"title": "Hen Feathers", "giver": "orrin", "level": 1, "min": 1, "after": ["word_with_elder"],
		"offer": "I'm writing a history of Ashvale. It needs a quill. It needs, in fact, several quills, because I press too hard. The hens by the fountain shed plenty — bring me six good ones. Don't hurt them more than necessary.",
		"goal": "Bring Sage Orrin 6 Hen Feathers.",
		"progress": "Quills don't grow on trees. Well. They grow on hens.", "done": "Splendid! Chapter one can begin. Take this — ink's worth more than it looks.",
		"obj": [{"kind": "collect", "item": "hen_feather", "n": 6, "from": ["hen"], "chance": 0.8}], "xp": 80, "items": ["sages_ink"], "rep": 25, "where": "around the fountain in the square"},
	"blacksmiths_wager": {"title": "The Blacksmith's Wager", "giver": "grom", "level": 2, "min": 1, "after": ["word_with_elder"],
		"offer": "Old Hale's scarecrows have come alive again — bad thread, I said, use good thread. Knock six of them down and I'll sharpen that toothpick you're carrying properly.",
		"goal": "Knock down 6 Walking Scarecrows in the west fields.",
		"progress": "Still standing, are they? The scarecrows, I mean.", "done": "Ha! Good thread, bad thread, it all burns. Here, I kept my word.",
		"obj": [{"kind": "kill", "mon": "scarecrow", "n": 6}], "xp": 120, "choice": ["sharpened_sword", "ashwood_wand"], "rep": 25, "where": "the west fields along the old road"},
	"grizzled_rat": {"title": "Grizzled Rat", "giver": "bess", "level": 3, "min": 2, "after": ["pests_in_fields"],
		"offer": "There's one rat the others answer to. Big as a dog, ugly as sin, lives under the granary. Deal with it and the rest will thin out on their own.",
		"goal": "Kill the Grizzled Rat under the granary.",
		"progress": "Is it dead? Tell me it's dead.", "done": "Dead? Good. I'll sleep tonight. Here — it was my husband's, back when he chased rats himself.",
		"obj": [{"kind": "kill", "mon": "grizzled_rat", "n": 1}], "xp": 150, "items": ["rat_catcher_cap"], "rep": 50, "where": "by the granary, north of the square"},
	"road_to_mill": {"title": "The Road to the Mill", "giver": "rowan", "ender": "hale", "level": 4, "min": 3, "after": ["pests_in_fields", "blacksmiths_wager"], "chain": "Welcome",
		"offer": "Farmer Hale at the Mill has been sending word for a week and I've had nobody to send. You'll do. Follow the east road past the fountain; it's safe as far as the fence. Give him this and tell him the fence is his problem.",
		"goal": "Take Rowan's Letter to Farmer Hale at the Mill.",
		"done": "A letter. From Rowan. About the fence. The fence.", "provide": ["rowans_letter"],
		"obj": [{"kind": "talk", "npc": "hale", "take": "rowans_letter"}], "xp": 140, "rep": 25, "where": "the Mill, along the east road"},
	# ================================================================ Hub 2 — the Mill
	"fence_can_wait": {"title": "The Fence Can Wait", "giver": "hale", "level": 4, "min": 3, "after": ["road_to_mill"], "chain": "Welcome",
		"offer": "There are boars in my beet field the size of carts and he writes about the fence. Right. Here's what I actually need: the boars gone, my brother found, and someone to look at what's rooting around the old shrine at night. Go and talk to Tomas, Wren and Captain Ada — they'll tell you the rest.",
		"goal": "Speak to Tomas, Wren the hunter and Guard Captain Ada at the Mill.",
		"done": "Right. Now you know everything I know, which is too much.",
		"obj": [{"kind": "talk", "npc": "tomas"}, {"kind": "talk", "npc": "wren"}, {"kind": "talk", "npc": "ada"}], "xp": 100, "rep": 25},
	"beet_thieves": {"title": "Beet Thieves", "giver": "hale", "level": 4, "min": 3, "after": ["fence_can_wait"],
		"offer": "Ten of them. I'd say more but I'd like you to come back.",
		"goal": "Kill 10 Wild Boars in the south fields.",
		"progress": "I can still hear them chewing.", "done": "Ten! My beets thank you. My wife thanks you. I thank you, mostly.",
		"obj": [{"kind": "kill", "mon": "wild_boar", "n": 10}], "xp": 200, "money": 600, "rep": 25, "where": "the fields south of the Mill"},
	"boar_hides": {"title": "Boar Hides", "giver": "tomas", "level": 4, "min": 3, "after": ["fence_can_wait"],
		"offer": "Hale won't let me near the boars since the thing with my leg. Bring me hides and I'll tan them. Bring me a lot of hides and I'll make you something.",
		"goal": "Bring Tomas 6 Boar Hides.",
		"progress": "Hides, friend. Hides.", "done": "Good hides, these. Here's a belt — first one I've made that didn't fall apart.",
		"obj": [{"kind": "collect", "item": "boar_hide", "n": 6, "from": ["wild_boar"], "chance": 0.7}], "xp": 160, "items": ["tanned_belt"], "rep": 25, "where": "the fields south of the Mill"},
	"something_in_woods": {"title": "Something in the Woods", "giver": "wren", "level": 5, "min": 4, "after": ["fence_can_wait"],
		"offer": "Wildcats have come down from the eastern woods. Bold ones. They took a lamb from the pen in daylight. I'll pay for eight — and if you see one with a torn ear, come and tell me.",
		"goal": "Kill 8 Wildcats at the edge of the eastern woods.",
		"progress": "Still hear them at night.", "done": "Eight. Good work. And the one with the torn ear? Thought not. Take one of these.",
		"obj": [{"kind": "kill", "mon": "wildcat", "n": 8}], "xp": 220, "choice": ["hunter_bracers", "woodland_sash"], "rep": 25, "where": "the edge of the eastern woods"},
	"lost_lamb": {"title": "Lost Lamb", "giver": "wren", "level": 5, "min": 4, "after": ["fence_can_wait"],
		"offer": "That lamb's still out there, bleating. Follow the sound past the split oak. Bring it back or bring me the bell, I'll know which.",
		"goal": "Find the lost lamb past the split oak and bring back its bell.",
		"done": "Well. That's one good thing today.",
		"obj": [{"kind": "gather", "item": "lamb_bell", "n": 1}], "xp": 180, "rep": 50, "where": "past the split oak, east of the Mill"},
	"old_scratch": {"title": "Old Scratch", "giver": "wren", "level": 7, "min": 6, "after": ["something_in_woods"],
		"offer": "Torn ear. Bigger than the rest. That's Old Scratch — he's the one bringing them down. He dens in the hollow oak. Take a friend if you've one.",
		"goal": "Kill Old Scratch at the hollow oak.",
		"progress": "He's clever, that one.", "done": "You got him. You actually got him. Keep the claw — it'll bring you luck, or at least a good price.",
		"obj": [{"kind": "kill", "mon": "old_scratch", "n": 1}], "xp": 300, "items": ["scratch_claw"], "rep": 50, "where": "the hollow oak in the eastern woods"},
	"night_at_shrine": {"title": "Night at the Shrine", "giver": "ada", "level": 5, "min": 4, "after": ["fence_can_wait"], "chain": "The Shrine",
		"offer": "Lights at the old shrine after dark, and my men won't go. Go and look. Just look — I want to know what it is before I lose anyone to it.",
		"goal": "Find out what is happening at the old shrine to the north-east.",
		"done": "Bones. Walking bones. I was hoping for smugglers.",
		"obj": [{"kind": "explore", "at": [72, -84], "r": 20.0, "name": "the Old Shrine", "spawn": ["skeleton_a", 2, 6]}]
, "xp": 200, "rep": 25, "where": "the old shrine, north-east of the Mill"},
	"bones_dont_walk": {"title": "Bones Don't Walk", "giver": "ada", "level": 7, "min": 6, "after": ["night_at_shrine"], "chain": "The Shrine",
		"offer": "Bones. Walking. Then someone made them walk. Put them down, and bring me anything on them that isn't bone.",
		"goal": "Destroy 8 Restless Bones at the shrine and bring back what they carry.",
		"progress": "Anything? Anything at all?", "done": "A token. From the mine. Well, well.",
		"obj": [{"kind": "kill", "mon": "restless_bones", "n": 8}, {"kind": "collect", "item": "grave_token", "n": 1, "from": ["restless_bones"], "chance": 0.2, "sure_after": 0}],

		"xp": 260, "choice": ["militia_bracer", "warding_charm"], "rep": 50, "where": "the shrine grounds"},
	"miners_mark": {"title": "The Miner's Mark", "giver": "ada", "level": 8, "min": 7, "after": ["bones_dont_walk"], "chain": "The Shrine",
		"offer": "This token's from the Hollow Mine — the Miners' Guild stamps everything. Someone's digging where they shouldn't. Take it to Foreman Gault at the Miners' Camp, north road past the shrine. Tell him Ada sent you, and tell him he owes me.",
		"goal": "Take the Grave Token to Foreman Gault at the Miners' Camp, up the north road past the wolves.",
		"ender": "gault", "done": "Ada sent you? Then she's worried, and Ada doesn't worry. That's our mark, all right. Stamped last month. Nobody's been down the old shafts since the rockfall... nobody who told me.",
		"obj": [{"kind": "talk", "npc": "gault", "take": "grave_token"}], "xp": 320, "rep": 75, "where": "the Miners' Camp, north up the Hollow Road"},
	"hogtooth": {"title": "Hogtooth, the Boar King", "group": true, "giver": "hale", "level": 9, "min": 7, "after": ["beet_thieves"],
		"offer": "You want to know why there are so many boars? Hogtooth. Tusks like ploughshares. He's out by the eastern woods and he's killed two dogs and a mule. I wouldn't go alone. I wouldn't go at all, but that's me.",
		"goal": "Kill Hogtooth, the Boar King, near the eastern woods. (Group)",
		"progress": "Still alive, isn't he. I can tell by the beets.", "done": "The Boar King! Dead! I'm going to tell everyone I helped.",
		"obj": [{"kind": "kill", "mon": "hogtooth", "n": 1}], "xp": 500, "choice": ["boar_king_tusk", "hogtooth_vest", "ploughshare_ring"], "rep": 150, "where": "the eastern woods, south of the hollow oak"},
	# ================================================================ Hub 3 — the Miners' Camp (10–16)
	"tokens_and_trouble": {"title": "Tokens and Trouble", "giver": "gault", "level": 10, "min": 9, "after": ["miners_mark"], "chain": "The Foreman",
		"offer": "Bats. Thousands of them, since the rockfall opened the Scree. They get in the lamps, they get in the stew, they got in Bram's hat and he hasn't been right since. Clear ten out of the Scree, west of camp, and I'll start taking you seriously.",
		"goal": "Kill 10 Cave Bats in the Scree, west of the camp.",
		"progress": "I can still hear them.", "done": "Ten. Good. You can swing a thing. Here — buy yourself something that doesn't smell of guano.",
		"obj": [{"kind": "kill", "mon": "cave_bat", "n": 10}], "xp": 420, "money": 900, "rep": 50, "where": "the Scree, west of the Miners' Camp"},
	"digging_where": {"title": "Digging Where They Shouldn't", "giver": "gault", "level": 11, "min": 10, "after": ["tokens_and_trouble"], "chain": "The Foreman",
		"offer": "Someone's been cutting black iron out of the old veins and it isn't my crews. I've marked the veins with chalk along Lantern Row and in the Upper Tunnels. Bring me eight pieces of what's left before it all walks off.",
		"goal": "Gather 8 Black Iron Ore from the chalk-marked veins on Lantern Row and in the Upper Tunnels.",
		"progress": "Eight. Black. Iron. Not rocks painted black, I've had that.", "done": "That's guild ore, cut with guild tools. Somebody inside the camp is selling us out. Keep that to yourself.",
		"obj": [{"kind": "gather", "item": "black_iron_ore", "n": 8}], "xp": 460, "choice": ["foremans_gauntlets", "lantern_row_cord"], "rep": 50, "where": "Lantern Row (north) and the Upper Tunnels (west)"},
	"foremans_key": {"title": "The Foreman's Key", "giver": "gault", "level": 13, "min": 11, "after": ["digging_where"], "chain": "The Foreman",
		"offer": "Skarr. Deep Foreman Skarr, who I sacked a year ago, has set up in the cut east of camp with a crew of diggers who used to be mine. He has the key to the old shafts. I want it. I want it more than I want him, and I want him a great deal.",
		"goal": "Kill Deep Foreman Skarr at Skarr's Cut and bring Gault Skarr's Key.",
		"progress": "The key. Have you got the key?", "done": "...That's it. That's the key to the Hollow. Leave it with me. You've done well. Get some rest.",
		"obj": [{"kind": "kill", "mon": "skarr", "n": 1}, {"kind": "collect", "item": "skarrs_key", "n": 1, "from": ["skarr"], "chance": 1.0}], "xp": 620, "money": 1500, "choice": ["diggers_pick", "cairn_warden_boots"], "rep": 75, "where": "Skarr's Cut, east of the camp"},
	"wheres_gault": {"title": "Where's Gault?", "giver": "hux", "ender": "vale", "level": 14, "min": 13, "after": ["foremans_key"], "chain": "The Foreman",
		"offer": "Have you seen the foreman? Took a lantern and your key and went up Lantern Row an hour ago. Said not to follow. Sister Vale was up at the cairns; she might have seen which way he went. I don't like it.",
		"goal": "Ask Sister Vale if she saw where Foreman Gault went.",
		"done": "I saw him. He went into the Hollow, and he wasn't alone, though I couldn't see who walked beside him. There's something under this mountain that has been whispering to the diggers for a year. I think Gault listened.",
		"obj": [{"kind": "talk", "npc": "vale"}], "xp": 300, "rep": 25},
	"into_the_hollow": {"title": "Into the Hollow", "giver": "vale", "level": 16, "min": 13, "after": ["wheres_gault"], "chain": "The Foreman", "group": true, "dungeon": "mine",
		"offer": "The mine mouth is at the top of Lantern Row. Don't go alone — find at least one other soul. Stop Foreman Gault if you can, and whatever sits in the deepest hall, put it back in the ground. It calls itself a king.",
		"goal": "In the Hollow Mine, defeat Foreman Gault and the Bone King. (Dungeon: group of 2 or more)",
		"progress": "You're back. Is it done?", "done": "Gault's dead, then. He was a good foreman, once. The mountain's quieter already — can you hear it? Take this, and thank you. The camp won't forget.",
		"obj": [{"kind": "kill", "mon": "gault", "n": 1}, {"kind": "kill", "mon": "bone_king", "n": 1}], "xp": 1600, "money": 3500, "choice": ["vale_prayer_beads", "enforcers_ring", "rockjaw_hide_cloak"], "rep": 250, "where": "the Hollow Mine, at the top of Lantern Row"},
	"maggot_stew": {"title": "Maggot Stew", "giver": "bram", "level": 11, "min": 10, "after": ["miners_mark"],
		"offer": "Don't make that face. Cave maggot's good eating if you boil it long enough and don't look at it. The Upper Tunnels, west and up. Eight good pieces. Big ones.",
		"goal": "Bring Bram 8 pieces of Maggot Meat from the Cave Maggots in the Upper Tunnels.",
		"progress": "Stew's not going to stew itself.", "done": "Look at that. Look at it. Tonight, we eat like foremen. Here, have a bowl on me. And these.",
		"obj": [{"kind": "collect", "item": "maggot_meat", "n": 8, "from": ["cave_maggot"], "chance": 0.75}], "xp": 440, "items": ["camp_cook_gloves"], "rep": 50, "where": "the Upper Tunnels, west of the camp"},
	"bear_took_pot": {"title": "The Bear Took My Pot", "giver": "bram", "level": 14, "min": 12, "after": ["maggot_stew"], "group": true,
		"offer": "Rockjaw. Big as a cart, bad as a debt collector. He came into camp, took my second-best pot, and walked off with it like he'd paid. South-east, in the den under the crag. Bring friends. Bring my pot.",
		"goal": "Kill Rockjaw in his den south-east of the camp. (Group)",
		"progress": "No pot, no stew.", "done": "My pot! A bit chewed. Still better than my first-best. Thank you — take this, he won't be needing it.",
		"obj": [{"kind": "kill", "mon": "rockjaw", "n": 1}], "xp": 760, "items": ["rockjaw_hide_cloak"], "rep": 75, "where": "Rockjaw's Den, south-east of the camp"},
	"rest_for_restless": {"title": "Rest for the Restless", "giver": "vale", "level": 12, "min": 11, "after": ["miners_mark"],
		"offer": "The miners who died in the rockfall are buried at the Cairn Field, up on the high ground north-west. Something has been disturbing them. Go and say the words over five of their graves — just stand by the stone and be still. I'll teach you the words. They're short.",
		"goal": "Bless 5 miners' graves at the Cairn Field, north-west of the camp.",
		"progress": "Did they rest?", "done": "Thank you. They were good people, most of them. The ones who weren't are resting too, now.",
		"obj": [{"kind": "gather", "item": "grave_blessing", "n": 5}], "xp": 480, "items": ["vale_prayer_beads"], "rep": 50, "where": "the Cairn Field, high up to the north-west"},
	"guild_business": {"title": "Guild Business", "giver": "hux", "level": 12, "min": 11, "after": ["miners_mark"],
		"offer": "Skarr's crews at the cut east of here are still digging in guild ground. Guild ground is guild business, and I'm the guild's business. Put eight of them down. Hard enough that they stay down.",
		"goal": "Defeat 8 Hollow Diggers at Skarr's Cut.",
		"progress": "The guild keeps count, you know.", "done": "Eight. Guild thanks you. Guild pays you, which is rarer.",
		"obj": [{"kind": "kill", "mon": "hollow_digger", "n": 8}], "xp": 520, "money": 1800, "rep": 50, "where": "Skarr's Cut, east of the camp"},
	"webs_on_rails": {"title": "Webs on the Rails", "giver": "hux", "level": 13, "min": 11, "after": ["guild_business"],
		"offer": "Lantern Row's full of spiders. The carts can't get through, and the lamp-lighter won't go up. Seven of them. Big ones count double, but I'm still paying for seven.",
		"goal": "Kill 7 Rail Spiders along Lantern Row, north of the camp.",
		"progress": "The lamp-lighter's still hiding in the tent.", "done": "Lantern Row's lit tonight for the first time in a month. That's your doing.",
		"obj": [{"kind": "kill", "mon": "rail_spider", "n": 7}], "xp": 540, "money": 1200, "rep": 50, "where": "Lantern Row, north of the camp"},
	"skarrs_enforcer": {"title": "Skarr's Enforcer", "giver": "hux", "level": 15, "min": 13, "after": ["foremans_key"], "group": true,
		"offer": "Skarr's dead but his enforcer isn't. Brak. Half man, half anvil, all temper. He's holed up past the cut, and the guild would like its cut back. Take friends; he's broken better folk than you.",
		"goal": "Defeat Brak, Skarr's Enforcer, beyond Skarr's Cut. (Group)",
		"progress": "Brak's still breathing. I can tell; the rocks are still shaking.", "done": "Brak down. The cut's ours again. Here — wear this and people will think twice.",
		"obj": [{"kind": "kill", "mon": "brak", "n": 1}], "xp": 800, "items": ["enforcers_ring"], "rep": 100, "where": "past Skarr's Cut, east"},
	"vales_letter": {"title": "A Letter for Mirewood", "giver": "vale", "level": 16, "min": 15, "after": ["into_the_hollow"], "chain": "The Road",
		"offer": "Warden Elsbeth at Mirewood Landing should hear about the Hollow from someone who was there. The Cliff Road runs east from the camp and down into the marsh. Take her this, and keep your boots dry.",
		"goal": "Take Sister Vale's letter to Warden Elsbeth at Mirewood Landing, east along the Cliff Road.",
		"done": "From Vale? She writes like she talks: short, and sure she's right. The Hollow, then. And now the goblins. It never rains in Mirewood but it pours.", "ender": "elsbeth", "provide": ["vales_letter"], "obj": [{"kind": "talk", "npc": "elsbeth", "take": "vales_letter"}], "xp": 400, "rep": 25},
	# ================================================================ Hub 4 — Mirewood Landing (14–22)
	"goblins_at_landing": {"title": "Goblins at the Landing", "giver": "elsbeth", "level": 15, "min": 14, "chain": "The Horn",
		"offer": "Goblins. Mire goblins, out of the shallows south of the road, stealing nets, stealing boats, stealing boots off sleeping wardens. Thin them out: twelve. Start with the camps along the east road.",
		"goal": "Kill 12 Mire Goblins in the Goblin Shallows, south of the east road.",
		"progress": "Still hearing them giggle at night.", "done": "Twelve. They'll think twice. Goblins can manage twice, just about.",
		"obj": [{"kind": "kill", "mon": "mire_goblin", "n": 12}], "xp": 700, "money": 2400, "choice": ["landing_wader_boots", "reedweave_mantle"], "rep": 50, "where": "the Goblin Shallows, south of the east road"},
	"shamans_totems": {"title": "The Shaman's Totems", "giver": "elsbeth", "level": 16, "min": 15, "after": ["goblins_at_landing"], "chain": "The Horn",
		"offer": "Their shamans plant totems in the camps — bones, feathers, a skull if they can find one. The goblins believe in them. Smash four and watch how brave they are then.",
		"goal": "Smash 4 goblin totems in the Goblin Shallows camps.",
		"progress": "Four totems. Smashed. Not admired.", "done": "Look at them run. Belief's a funny thing.",
		"obj": [{"kind": "gather", "item": "totem_smashed", "n": 4}], "xp": 720, "money": 1800, "rep": 50, "where": "the goblin camps, south of the east road"},
	"warlords_lieutenant": {"title": "The Warlord's Lieutenant", "giver": "elsbeth", "level": 17, "min": 16, "after": ["shamans_totems"], "chain": "The Horn",
		"offer": "There's a goblin called Grisk running the camps for someone bigger. Kill Grisk and the someone bigger has to come out himself. He's at the camp furthest east, by the old bridge.",
		"goal": "Kill Grisk, the Warlord's Lieutenant, at the goblin camp by the old bridge in the east.",
		"progress": "Grisk still breathing?", "done": "Grisk's dead. Now we wait for the Warlord to lose his temper. Won't be long.",
		"obj": [{"kind": "kill", "mon": "goblin_lieutenant", "n": 1}], "xp": 900, "choice": ["wardens_halberd", "ferrymans_cord"], "rep": 75, "where": "by the old bridge, far east"},
	"the_horn": {"title": "The Horn", "giver": "elsbeth", "level": 19, "min": 17, "after": ["warlords_lieutenant"], "chain": "The Horn", "group": true,
		"offer": "Gorvok the Warlord has come out of the Sunken Camp, east past the shallows, and he's angry. Take friends. Bring me his horn: whoever blows it, goblins follow. We'd rather nobody blew it.",
		"goal": "Kill Gorvok the Goblin Warlord at the Sunken Camp and bring Elsbeth the Warlord's Horn. (Group)",
		"progress": "The horn. Have you got the horn?", "done": "There it is. Ugly thing. You know what, keep it — a thing like that could found a guild. Just don't blow it in my Landing.",
		"obj": [{"kind": "kill", "mon": "goblin_warlord", "n": 1}, {"kind": "collect", "item": "warlords_horn", "n": 1, "from": ["goblin_warlord"], "chance": 1.0}],
		"xp": 1500, "money": 5000, "choice": ["mirewarden_signet", "barkskin_legguards"], "rep": 150, "where": "the Sunken Camp, east"},
	"viper_glands": {"title": "Viper Glands", "giver": "dodd", "level": 15, "min": 14,
		"offer": "Reed vipers. Bite's nasty, venom's worth a mint to the right buyer. That's Ivo. Bring me eight glands from the reed banks up north-west and I'll sell 'em to her, and you'll get a cut. A fair cut. Ferryman's honour.",
		"goal": "Collect 8 Viper Venom Glands from Reed Vipers on the reed banks, north-west of the Landing.",
		"progress": "Watch your ankles.", "done": "Lovely. Oozing. Here's your cut — don't count it in front of me, it's rude.",
		"obj": [{"kind": "collect", "item": "viper_gland", "n": 8, "from": ["viper"], "chance": 0.7}], "xp": 700, "money": 3000, "rep": 50, "where": "the reed banks, north-west of the Landing"},
	"moth_dust": {"title": "Moth Dust", "giver": "ivo", "level": 16, "min": 15,
		"offer": "Temple moths come down out of the ash country to die in my marsh. Their dust makes the best sleeping draught you've never tasted. Six wings' worth. They're in the hollow north-west, by the dead trees. They bite. A little.",
		"goal": "Collect 6 Temple Moth Dust from Temple Moths in the Broodmother's Hollow, north-west.",
		"progress": "Dust. Moth dust.", "done": "Perfect. Take this charm; I made two. One of them works.",
		"obj": [{"kind": "collect", "item": "moth_dust", "n": 6, "from": ["temple_moth"], "chance": 0.75}], "xp": 720, "items": ["witchs_charm"], "rep": 50, "where": "the Broodmother's Hollow, north-west"},
	"hold_the_bridge": {"title": "Hold the Bridge", "giver": "fenn", "level": 17, "min": 16,
		"offer": "The old bridge on the east road. The goblins keep coming across it at night. I'm meant to hold it. I'm one man. You're one person. Together we're... two. Put down eight of them at the bridge camp and we'll call it held.",
		"goal": "Kill 8 goblins at the camp by the old bridge in the east.",
		"progress": "The bridge still isn't held.", "done": "Held! Put that in the report. Actually, don't; I'll put it in.",
		"obj": [{"kind": "kill", "mon": "mire_goblin", "n": 8}], "xp": 780, "items": ["fenns_bracers"], "rep": 75, "where": "the old bridge, far east of the Landing"},
	"marsh_stalkers": {"title": "Something Big in the Reeds", "giver": "fenn", "level": 18, "min": 17, "after": ["hold_the_bridge"],
		"offer": "Stalkers. Tall, hairy, fast. They hunt along the Drowned Road at dusk and take anyone slower than them, which is everyone. Six. Please.",
		"goal": "Kill 6 Marsh Stalkers along the Drowned Road, south-east.",
		"progress": "Hear that howl? That's them. That's still them.", "done": "Six. I'll sleep. You should too.",
		"obj": [{"kind": "kill", "mon": "marsh_stalker", "n": 6}], "xp": 840, "money": 3500, "rep": 50, "where": "along the Drowned Road, south-east"},
	"into_the_warrens": {"title": "The Warrens", "giver": "ivo", "level": 21, "min": 18, "after": ["moth_dust"], "group": true, "dungeon": "warrens",
		"offer": "The old hollow tree north-east of the marsh. There are warrens under it, older than the Landing, and something has been breeding down there — spiders the size of boats, and a root that walks. Take friends. Kill the mother, and the root. Bring me nothing; just come back.",
		"goal": "In the Warrens under the hollow tree, defeat the Broodmother and Old Rootmaw. (Dungeon: group of 2 or more)",
		"progress": "Still breeding, is it?", "done": "The marsh is breathing easier. So am I. Here — you've earned something from the good shelf.",
		"obj": [{"kind": "kill", "mon": "broodmother", "n": 1}, {"kind": "kill", "mon": "rootmaw", "n": 1}], "xp": 2400, "money": 8000, "choice": ["witchs_charm", "wardens_halberd", "reedweave_mantle"], "rep": 250, "where": "the Warrens, under the hollow tree to the north-east"},
	"elsbeths_map": {"title": "The Shaman's Map", "giver": "elsbeth", "ender": "sorin", "level": 20, "min": 19, "after": ["the_horn"], "chain": "The Road", "provide": ["elsbeths_map"],
		"offer": "We found this on Gorvok. A map, and a skull drawn on the Temple of Ash across the water. Abbot Sorin at Temple Gate should see it. Take the Ashwater Crossing east, and give him my regards. He won't want them.",
		"goal": "Take the Shaman's Map to Abbot Sorin at Temple Gate, over the Ashwater Crossing to the east.",
		"done": "", "obj": [{"kind": "talk", "npc": "sorin", "take": "elsbeths_map"}], "xp": 600, "rep": 25},
	# ================================================================ Hub 5 — Temple Gate, the Ash Slopes (20–28)
	"stone_sentinels": {"title": "Stone Sentinels", "giver": "sorin", "level": 21, "min": 20, "after": ["elsbeths_map"], "chain": "The Temple",
		"offer": "The cultists woke the sentinels that used to guard our stair. Now they guard nothing, and hit everything. Break eight of them in the cinder fields west of the Gate, and bring me the cores so they don't wake again.",
		"goal": "Destroy 8 Stone Sentinels in the Cinder Fields and bring back their cores.",
		"progress": "Eight cores, please. They hum when they're close.", "done": "Quiet now. Good. The stair can breathe.",
		"obj": [{"kind": "kill", "mon": "stone_sentinel", "n": 8}, {"kind": "collect", "item": "sentinel_core", "n": 8, "from": ["stone_sentinel"], "chance": 1.0}],
		"xp": 1100, "money": 5000, "choice": ["pilgrims_robe", "temple_guard_girdle"], "rep": 75, "where": "the Cinder Fields, west of Temple Gate"},
	"cultists_want": {"title": "What the Cultists Want", "giver": "sorin", "level": 22, "min": 21, "after": ["stone_sentinels"], "chain": "The Temple",
		"offer": "The Khar keep ledgers. Everything is written down: who, when, how much ash. Take six from the cultists on the Charnel Steps, north-west, and we'll know what they want.",
		"goal": "Collect 6 Khar Ledgers from the cultists on the Charnel Steps, north-west of the Gate.",
		"progress": "Ledgers. They carry them everywhere, like prayer books.", "done": "Six. Now we need someone who can read their hand. Fortunately, we caught one.",
		"obj": [{"kind": "collect", "item": "khar_ledger", "n": 6, "from": ["khar_cultist", "khar_zealot"], "chance": 0.6}], "xp": 1150, "money": 5000, "rep": 75, "where": "the Charnel Steps, north-west"},
	"prisoner_talks": {"title": "The Prisoner Talks", "giver": "sorin", "ender": "prisoner", "level": 23, "min": 22, "after": ["cultists_want"], "chain": "The Temple",
		"offer": "Take the ledgers to our prisoner. He says he won't talk without them. I think he's lonely.",
		"goal": "Take the Khar Ledgers to the Prisoner at Temple Gate.",
		"done": "...These are hers. Mora's. She's in the temple, under the bell, draining the souls of everyone the Khar bring her. Stop her and I'll tell you everything. Don't, and it doesn't matter what I tell you.",
		"obj": [{"kind": "talk", "npc": "prisoner"}], "xp": 600, "rep": 25},
	"high_cultist_mora": {"title": "High Cultist Mora", "giver": "prisoner", "ender": "sorin", "level": 27, "min": 24, "after": ["prisoner_talks"], "chain": "The Temple", "group": true, "dungeon": "temple",
		"offer": "The temple door is at the top of the stair, north. Brother Kel rings the bell; the bell knocks you senseless. Ashmaw burns. And Mora... when she starts to drain someone, hit her. Hard. It's the only thing that breaks her focus.",
		"goal": "In the Temple of Ash, defeat High Cultist Mora. (Dungeon: group of 2 or more)",
		"progress": "Is she gone?", "done": "The bell is quiet. The temple is ours again — scorched, but ours. Take this, with the Order's thanks, and take her seal to Highland Watch. They should know the Khar have friends in the mountains.",
		"obj": [{"kind": "kill", "mon": "mora", "n": 1}], "xp": 3200, "money": 15000, "choice": ["abbots_prayer_staff", "cindersteel_helm", "masons_hammer"], "rep": 300, "where": "the Temple of Ash, top of the stair"},
	"guardian_arrows": {"title": "Guardian Arrows", "giver": "nell", "level": 22, "min": 21,
		"offer": "The cultists turned our own archers. Temple Archers, on the Pilgrims' Road east. They're shooting our arrows at us — fletched by my own hand. Bring me ten back.",
		"goal": "Recover 10 Guardian Arrows from the Temple Archers along the Pilgrims' Road, east.",
		"progress": "I count every arrow I make. That's how I know.", "done": "My fletching. My poor fletching. Thank you. Wear this; it keeps your aim.",
		"obj": [{"kind": "collect", "item": "guardian_arrow", "n": 10, "from": ["temple_archer"], "chance": 0.8}], "xp": 1100, "items": ["nells_longbow_charm"], "rep": 75, "where": "the Pilgrims' Road, east of the Gate"},
	"broken_statues": {"title": "Broken Statues", "giver": "pell", "level": 23, "min": 22,
		"offer": "Four statues on the slopes I've not seen since the Khar came. The Weeping Saint, west. The Bell-Keeper, by the stair. The Pilgrim, east. The Old Abbot, up by the ridge. Go and look at them for me. Tell me if they're still standing.",
		"goal": "Visit the four old statues of the Ash Slopes.",
		"progress": "Well?", "done": "Standing, all four. Cracked, scorched, rude words scratched on the Pilgrim — but standing. Here, you've earned this.",
		"obj": [{"kind": "explore", "at": [-60, 12], "r": 8.0, "name": "the Weeping Saint"}, {"kind": "explore", "at": [4, -58], "r": 8.0, "name": "the Bell-Keeper"},
			{"kind": "explore", "at": [70, -20], "r": 8.0, "name": "the Pilgrim"}, {"kind": "explore", "at": [-30, -80], "r": 8.0, "name": "the Old Abbot"}],
		"xp": 1150, "items": ["masons_hammer"], "rep": 50},
	"ashen_imps": {"title": "Imps in the Cinders", "giver": "nell", "level": 24, "min": 23, "after": ["guardian_arrows"],
		"offer": "Imps. Little burning things, coming up out of the vents south-east. They set fire to the stables twice last week. Ten of them, before they set fire to anything else.",
		"goal": "Kill 10 Cinder Imps at the vents south-east of Temple Gate.",
		"progress": "Smell that? Burning hay.", "done": "Ten. The stables thank you. The horse doesn't, but she never does.",
		"obj": [{"kind": "kill", "mon": "cinder_imp", "n": 10}], "xp": 1200, "money": 6000, "rep": 50, "where": "the vents, south-east of the Gate"},
	"the_stone_warden": {"title": "The Stone Warden", "giver": "pell", "level": 26, "min": 24, "after": ["broken_statues"], "group": true,
		"offer": "There's one sentinel the cultists didn't wake. The Stone Warden. It woke itself. It's up on the Bell Tower ridge, north-east, and it's the biggest thing I ever carved. I'm sorry. Take friends.",
		"goal": "Defeat the Stone Warden on the ridge north-east of the Gate. (Group)",
		"progress": "Still standing? Of course it is. I carved it well.", "done": "Rubble. My best work, rubble. You did the right thing. Here.",
		"obj": [{"kind": "kill", "mon": "stone_warden", "n": 1}], "xp": 1800, "items": ["cindersteel_helm"], "rep": 100, "where": "the ridge, north-east of the Gate"},
	"moras_seal": {"title": "Mora's Seal", "giver": "sorin", "ender": "roark", "level": 27, "min": 26, "after": ["high_cultist_mora"], "chain": "The Road", "provide": ["moras_seal"],
		"offer": "Captain Roark at Highland Watch, over the High Pass north-east. Give him Mora's seal. Tell him the Khar are coming down out of the mountains, and ask him how he'd like to be ready.",
		"goal": "Take Mora's Seal to Captain Roark at Highland Watch, over the High Pass to the north-east.",
		"done": "", "obj": [{"kind": "talk", "npc": "roark", "take": "moras_seal"}], "xp": 900, "rep": 25},
	"a_horse_is_a_horse": {"title": "A Horse Is a Horse", "giver": "stablehand", "level": 24, "min": 24, "chain": "The Mount",
		"offer": "You want to ride? Everybody wants to ride. Here's the thing: I've one horse and she's mine. But there are wild ones up in the Highlands, and they come for oats. Highland oats. Bring me ten from the fields up there and I'll teach you how to catch one.",
		"goal": "Gather 10 Highland Oats in the Ashen Highlands, over the High Pass.",
		"progress": "Oats. Highland ones. The lowland ones make them sulk.", "done": "That's the stuff. Now: go and find a stray up there. Don't chase it. Let it come to you.",
		"obj": [{"kind": "gather", "item": "highland_oats", "n": 10}], "xp": 900, "rep": 25, "where": "the oat fields of the Ashen Highlands"},
	# ================================================================ Hub 6 — Highland Watch, the Ashen Highlands (26–34)
	"khar_on_ridge": {"title": "Khar on the Ridge", "giver": "roark", "level": 27, "min": 26, "after": ["moras_seal"], "chain": "The Khar",
		"offer": "Beastmen. Khar, they call themselves, and they walk on two legs when they remember. They've a camp on the north road. Ten of them, and they'll know we're awake.",
		"goal": "Kill 10 Khar Beastmen along the north road.",
		"progress": "Still howling up there.", "done": "Ten. They'll send more. They always send more. Good work.",
		"obj": [{"kind": "kill", "mon": "khar_beastman", "n": 10}], "xp": 1600, "money": 9000, "choice": ["heather_cloak", "watch_pauldrons"], "rep": 75, "where": "the north road, towards the Plateau Road"},
	"bulls_trail": {"title": "The Bull's Trail", "giver": "roark", "level": 28, "min": 27, "after": ["khar_on_ridge"], "chain": "The Khar",
		"offer": "Something big walks the east shore at night. Hoofprints the size of shields. Follow them — the drinking place by the lake and the scorched rocks past it. Look. Don't fight.",
		"goal": "Follow the Bull's Trail: the drinking place on the east shore, and the scorched rocks beyond.",
		"progress": "Well? What did you see?", "done": "The Bull of Khar. So he's real. Ned will be unbearable.",
		"obj": [{"kind": "explore", "at": [56, 10], "r": 9.0, "name": "the drinking place"}, {"kind": "explore", "at": [80, -20], "r": 9.0, "name": "the scorched rocks"}], "xp": 1500, "rep": 50},
	"khar_elites": {"title": "Khar Bloodguard", "giver": "roark", "level": 30, "min": 28, "after": ["bulls_trail"], "chain": "The Khar",
		"offer": "The Outpost up on the north-east ridge. Bloodguard, their best. Kill four and bring the ridge back to us.",
		"goal": "Kill 4 Khar Bloodguard at the Khar Outpost, north-east.",
		"progress": "Four. Their best.", "done": "The Outpost's quiet. Brandmaster Ghor will come himself now.",
		"obj": [{"kind": "kill", "mon": "khar_elite", "n": 4}], "xp": 1900, "money": 11000, "rep": 75, "where": "the Khar Outpost, north-east ridge"},
	"brandmaster": {"title": "The Minotaur's Brand", "giver": "roark", "level": 31, "min": 29, "after": ["khar_elites"], "chain": "The Khar",
		"offer": "Ghor the Brandmaster. He brands the Khar young so they know whose they are. End him.",
		"goal": "Kill Ghor the Brandmaster at the Khar Outpost.",
		"progress": "Ghor.", "done": "The brand is broken. Take his axe — it's a good axe, even if he wasn't.",
		"obj": [{"kind": "kill", "mon": "brandmaster", "n": 1}], "xp": 2200, "choice": ["brandmasters_axe", "raiders_band"], "rep": 100, "where": "the Khar Outpost"},
	"roarks_dispatch": {"title": "Siege Preparations", "giver": "roark", "ender": "greaves", "level": 33, "min": 31, "after": ["brandmaster"], "chain": "The Road", "provide": ["roarks_dispatch"],
		"offer": "Marshal Greaves holds Varn's Rest on the plateau, south up the Plateau Road. He needs to know what we've learned. Take him this.",
		"goal": "Take Roark's Dispatch to Marshal Greaves at Varn's Rest, up the Plateau Road.",
		"done": "Roark writes like a man who's been cold for thirty years. Good. You'll be needed here.", "obj": [{"kind": "talk", "npc": "greaves", "take": "roarks_dispatch"}], "xp": 1200, "rep": 25},
	"highland_bloom": {"title": "Highland Bloom", "giver": "mira", "level": 27, "min": 26,
		"offer": "Highland bloom grows in the heather all over the slopes — purple, with a yellow eye. Eight stems. I'll make you something for the cold.",
		"goal": "Gather 8 Highland Bloom from the heather.",
		"progress": "The purple ones. With the eye.", "done": "Perfect. Here — you'll want these when the wind comes.",
		"obj": [{"kind": "gather", "item": "highland_bloom", "n": 8}], "xp": 1500, "items": ["herbalists_gloves"], "rep": 50, "where": "the heather slopes"},
	"highland_wolves": {"title": "Grey Runners", "giver": "oda", "level": 28, "min": 27,
		"offer": "Wolves took three of our supply ponies this month. Twelve of them, please. I'll put it in the ledger as 'pest control'.",
		"goal": "Kill 12 Highland Wolves in the western hills.",
		"progress": "Twelve, the ledger says.", "done": "Ledger balanced. That's the nicest thing I can say about anything.",
		"obj": [{"kind": "kill", "mon": "highland_wolf", "n": 12}], "xp": 1600, "money": 12000, "rep": 50, "where": "the western hills"},
	"stories_of_sanctum": {"title": "Stories of the Sanctum", "giver": "ned", "ender": "tessaly", "level": 32, "min": 30, "chain": "Attunement", "provide": ["neds_notes"],
		"offer": "The Sanctum. You'll hear the young ones talk about it like it's a tavern. It isn't. Take my notes to Tessaly at Varn's Rest. She knows the way in. She'll say you're not ready. You're not. Go anyway.",
		"goal": "Take Old Ned's Notes to Tessaly the Lich-Hunter at Varn's Rest.",
		"done": "Ned's still alive? And still writing? The way in is through the Catacombs. First, though, you'll help me.", "obj": [{"kind": "talk", "npc": "tessaly", "take": "neds_notes"}], "xp": 1400, "rep": 25},
	"bull_of_khar": {"title": "The Bull of Khar", "giver": "ned", "level": 33, "min": 31, "after": ["bulls_trail"], "group": true,
		"offer": "Roark says you saw the Bull. I fought him once. Lost. Take three friends. Win.",
		"goal": "Defeat the Bull of Khar by the scorched rocks, east. (Group)",
		"progress": "Well?", "done": "Dead? Ha! Forty years. Here — my old band. It never did me any good; maybe it'll do you some.",
		"obj": [{"kind": "kill", "mon": "bull_of_khar", "n": 1}], "xp": 2800, "items": ["raiders_band"], "rep": 150, "where": "the scorched rocks, east of the lake"},
	"sunken_crypts": {"title": "The Drowned Dead", "giver": "mira", "level": 33, "min": 30, "group": true, "dungeon": "crypts",
		"offer": "The mausoleum by the lake. The dead in the crypts underneath are walking, and they're walking into my lake. Lady Silt and the Crypt Lord. Put them back. Take friends.",
		"goal": "In the Sunken Crypts, defeat Lady Silt and the Crypt Lord. (Dungeon: group of 2 or more)",
		"progress": "The lake's still cold. Colder.", "done": "The lake's warming. Well — less cold. Thank you. Choose something.",
		"obj": [{"kind": "kill", "mon": "lady_silt", "n": 1}, {"kind": "kill", "mon": "crypt_lord", "n": 1}], "xp": 4800, "money": 30000, "choice": ["herbalists_gloves", "heather_cloak", "brandmasters_axe"], "rep": 300, "where": "the mausoleum by the lake, east"},
	"the_stray": {"title": "The Stray", "giver": "stablehand", "ender": "stray", "level": 26, "min": 24, "after": ["a_horse_is_a_horse"], "chain": "The Mount",
		"offer": "There's a wild stag that comes to the oat field in the west of the Highlands. Not a horse, no, but it'll carry you and it's a sight kinder. Go and find it. Stand still. Let it come.",
		"goal": "Find the wild stag by the western oat field in the Ashen Highlands.",
		"done": "The stag lowers its head and snorts at the oats in your hand. It doesn't run.", "obj": [{"kind": "talk", "npc": "stray"}], "xp": 900, "rep": 25},
	"gentling": {"title": "Gentling", "giver": "stray", "level": 28, "min": 24, "after": ["the_stray"], "chain": "The Mount",
		"offer": "The stag nudges your pocket. It will come to you, but not all at once. Feed it — on three different days.",
		"goal": "Feed the wild stag on three different days.",
		"progress": "The stag watches you, waiting.", "done": "On the third day the stag walks to meet you across the field. It's yours, if you can find it a saddle.",
		"obj": [{"kind": "daily", "npc": "stray", "n": 3}], "xp": 1200, "rep": 25},
	# ================================================================ Hub 7 — Varn's Rest, the Varn Plateau (34–40)
	"wraiths_on_road": {"title": "Wraiths on the Road", "giver": "greaves", "level": 35, "min": 34, "after": ["roarks_dispatch"], "chain": "The Sanctum Gate",
		"offer": "The Fallen Ward, west of the camp. The dead of the last war, and they don't know it's over. Fifteen. Put them down.",
		"goal": "Destroy 15 Fallen Wraiths in the Fallen Ward, west.",
		"progress": "They're still marching.", "done": "Fifteen fewer. It's a start. It's always a start here.",
		"obj": [{"kind": "kill", "mon": "fallen_wraith", "n": 15}], "xp": 2400, "money": 18000, "rep": 75, "where": "the Fallen Ward, west of Varn's Rest"},
	"acolytes_circle": {"title": "The Acolytes' Circle", "giver": "greaves", "level": 36, "min": 35, "after": ["wraiths_on_road"], "chain": "The Sanctum Gate",
		"offer": "Three acolytes at the standing stones east of here raise them faster than we can bury them. Veyne, Marr and Soth. Three names. Three graves.",
		"goal": "Kill the three acolytes at the Acolytes' Circle, east.",
		"progress": "Names, and graves.", "done": "Three graves. I'll have them marked.",
		"obj": [{"kind": "kill", "mon": "circle_acolyte", "n": 3}], "xp": 2800, "choice": ["marshals_girdle", "lichhunter_wraps"], "rep": 100, "where": "the Acolytes' Circle, east"},
	"abyssal_knights": {"title": "Abyssal Knights", "giver": "greaves", "level": 37, "min": 36, "after": ["acolytes_circle"], "chain": "The Sanctum Gate",
		"offer": "The Killing Ground, south of the keep. Knights in black armour that burn. Six.",
		"goal": "Defeat 6 Abyssal Knights on the Killing Ground, south of Castle Varn.",
		"progress": "Six knights.", "done": "Six. You've more steel in you than they have.",
		"obj": [{"kind": "kill", "mon": "abyssal_knight", "n": 6}], "xp": 3000, "money": 24000, "rep": 100, "where": "the Killing Ground, south of the keep"},
	"the_catacombs": {"title": "The Catacombs", "giver": "greaves", "level": 40, "min": 37, "after": ["abyssal_knights"], "chain": "The Sanctum Gate", "group": true, "dungeon": "catacombs",
		"offer": "Under the keep. The Gravewarden guards the way down and Lord Varn himself sits at the bottom — what's left of him. End the Hollow Lich and the plateau is ours. Take your best friends.",
		"goal": "In the Varn Catacombs, defeat the Gravewarden and Lord Varn. (Dungeon: group of 2 or more)",
		"progress": "Is Varn gone?", "done": "The Hollow Lich is dust. Four hundred years, and it took you. Choose — and then go and see the Keeper. He'll have something to say about the Sanctum.",
		"obj": [{"kind": "kill", "mon": "gravewarden", "n": 1}, {"kind": "kill", "mon": "lord_varn", "n": 1}], "xp": 8000, "money": 60000, "choice": ["marshals_girdle", "lichhunter_wraps", "varn_signet"], "rep": 400, "where": "the Catacomb Arch, under Castle Varn"},
	"attunement_sanctum": {"title": "Attunement: The Sanctum Gate", "giver": "sanctum_qm", "level": 40, "min": 40, "after": ["the_catacombs", "stories_of_sanctum"], "chain": "Attunement",
		"offer": "You killed Varn. Tessaly vouches for you. Old Ned thinks you're a fool. That's everyone who matters. Take the key. The Gate is north-east, where the light is wrong.",
		"goal": "Speak with Keeper Ansel to receive the Sanctum Key.",
		"done": "The Sanctum Gate will open for you and for anyone you bring. Come back alive.", "obj": [{"kind": "talk", "npc": "sanctum_qm"}], "xp": 2000, "items": ["sanctum_key"], "rep": 100},
	"soul_shards": {"title": "Soul Shards", "giver": "tessaly", "level": 36, "min": 34,
		"offer": "When a wraith falls, sometimes a shard of the soul it stole falls too. Bring them to me and I'll send them home. Ten.",
		"goal": "Collect 10 Soul Shards from Fallen Wraiths.",
		"progress": "Ten souls, waiting.", "done": "Home. All ten. Thank you.",
		"obj": [{"kind": "collect", "item": "soul_shard", "n": 10, "from": ["fallen_wraith"], "chance": 0.55}], "xp": 2500, "money": 20000, "rep": 75, "where": "the Fallen Ward, west"},
	"vaals_herald": {"title": "Vaal's Herald", "giver": "tessaly", "level": 39, "min": 37, "group": true,
		"offer": "Something speaks for Vaal at the Black Chapel, west. A herald. It says the Sanctum is waiting for us. Shut it up. Bring four friends if you can find them.",
		"goal": "Defeat Vaal's Herald at the Black Chapel, west. (Group)",
		"progress": "It's still talking. I can hear it in my sleep.", "done": "Quiet. Blessed quiet.",
		"obj": [{"kind": "kill", "mon": "vaals_herald", "n": 1}], "xp": 4000, "items": ["varn_signet"], "rep": 150, "where": "the Black Chapel, west"},
	"saddle_and_shoes": {"title": "Saddle and Shoes", "giver": "durn", "level": 36, "min": 34, "after": ["gentling"], "chain": "The Mount",
		"offer": "A stag? You want a saddle for a stag. Fine. Bring me six Black Iron Bars for the fittings and four pieces of Rugged Leather for the seat. I'll do the rest.",
		"goal": "Bring Smith Durn 6 Black Iron Bars and 4 Rugged Leather.",
		"progress": "Bars and leather. I can't make a saddle out of wishes.", "done": "There. Best saddle I've made for anything with antlers. Now ride it home — all the way to Ashvale, and tell Rowan I said hello.",
		"obj": [{"kind": "gather", "item": "bar_2", "n": 6}, {"kind": "gather", "item": "leather_2", "n": 4}], "xp": 2000, "rep": 50},
	"the_long_ride": {"title": "The Long Ride", "giver": "durn", "ender": "rowan", "level": 38, "min": 34, "after": ["saddle_and_shoes"], "chain": "The Mount",
		"offer": "The stag's saddled and waiting by the gate. Ride it home. The long way — every road you came up, back down to Ashvale. Rowan's got the papers.",
		"goal": "Ride all the way back to Ashvale and speak to Elder Rowan.",
		"done": "You rode all that way? On that? ...It's magnificent. It needs papers. Everything needs papers.", "obj": [{"kind": "talk", "npc": "rowan"}], "xp": 2400, "rep": 50},
	"yours": {"title": "Yours", "giver": "rowan", "level": 40, "min": 36, "after": ["the_long_ride"], "chain": "The Mount", "cost": 1000000,
		"offer": "One hundred gold for the papers. Don't look at me like that, it's the law, and I didn't write it. Well — I did write it. It's still the law.",
		"goal": "Pay Elder Rowan 100 gold for the stag's papers.",
		"done": "There. Signed, stamped, yours. Ride well. And come and visit — the town doesn't get many heroes on stags.",
		"obj": [{"kind": "talk", "npc": "rowan"}], "xp": 1000, "mount": true, "rep": 100},
	"old_tusk": {"title": "Old Tusk",



 "giver": "hale", "level": 10, "min": 8, "needs_item": "old_tusks_tusk",
		"offer": "Is that — you killed Old Tusk? The one from the stories? My father swore that boar ate a plough. Give it here, let me look at it.",
		"goal": "Show Old Tusk's tusk to Farmer Hale.",
		"done": "You killed Old Tusk? The one from the stories? Have a drink. Have two. And take this — it was meant for whoever did it.",
		"obj": [{"kind": "talk", "npc": "hale", "take": "old_tusks_tusk"}], "xp": 400, "items": ["tusk_blue"], "rep": 100},
	"rowans_history": {"title": "Rowan's History",
 "giver": "orrin", "level": 8, "min": 6, "after": ["night_at_shrine"],
		"offer": "The shrine! Nobody's been in a decade. Bring me anything old — coins, tokens, a nice bit of pot — and I'll put you in the history. A footnote, but still.",
		"goal": "Pick up 5 Old Coins at the old shrine for Sage Orrin.",
		"progress": "Old things, from old places.", "done": "Marvellous. You, my friend, are now a footnote. Wear it with pride.",
		"obj": [{"kind": "gather", "item": "old_coin", "n": 5}], "xp": 200, "title_reward": "the Footnote", "rep": 25, "where": "the old shrine"},
	# ================================================================ Milestone 6 — levels 40–60: Gullhaven, Forgehold, Wintermere, the Last Watch
	"the_salt_road": {"title": "The Salt Road", "giver": "greaves", "ender": "maren", "level": 40, "min": 39, "after": ["abyssal_knights"], "chain": "The Salt Road", "provide": ["greaves_requisition"],
		"offer": "We eat salt fish and we mend our mail with Gullhaven rivets. Both have stopped coming. Take this requisition down the Salt Road to the harbormaster, Maren Holt, and find out why. Politely. Then less politely, if you have to.",
		"goal": "Take Marshal Greaves' requisition east along the Salt Road to Harbormaster Maren Holt in Gullhaven.", "done": "Greaves wants fish. Everyone wants fish. Nobody wants to hear why there isn't any. Sit down — I'll tell you anyway.",
		"obj": [{"kind": "talk", "npc": "maren", "take": "greaves_requisition"}], "xp": 3350, "money": 20100, "rep": 75},
	"crabs_in_the_nets": {"title": "Crabs in the Nets", "giver": "maren", "level": 40, "min": 39, "chain": "The Salt Road",
		"offer": "The tide crabs came up out of the deep water a month ago, big as barrels, and they've been cutting our nets for sport. You can't fish with a net that's more hole than net. Thin them out on the Kelp Flats and my boats can go back out.",
		"goal": "Kill 12 Tide Crabs on the Kelp Flats, east of Gullhaven.", "progress": "Still clicking out there, are they?", "done": "Twelve. I heard the boats cheer from the pier. That's the first cheer in Gullhaven since the spring.",
		"obj": [{"kind": "kill", "mon": "tide_crab", "n": 12}], "xp": 6650, "money": 39900, "choice": ["netmenders_gloves", "saltwind_cord", "harbor_watch_girdle"], "rep": 75, "where": "the Kelp Flats, east of town"},
	"chowder": {"title": "Gullhaven Chowder", "giver": "cask", "level": 40, "min": 39,
		"offer": "My chowder's the only thing in this town that hasn't gone wrong. I mean to keep it that way, and it wants crab. The big ones on the flats have claws the size of your arm and sweet as butter. Eight of them. I'll feed you for a week.",
		"goal": "Bring Cask 8 Tender Claws from Tide Crabs.", "progress": "The pot's on. The pot is waiting.", "done": "Look at that meat. Right, that's supper for the whole town, and there's a bowl in it for you. Two bowls. Don't argue.",
		"obj": [{"kind": "collect", "item": "tender_claw", "n": 8, "from": ["tide_crab"], "chance": 0.6}], "xp": 6650, "money": 39900, "items": ["gullhaven_chowder"], "rep": 75, "where": "the Kelp Flats, east of town"},
	"wreckers_cove": {"title": "Wreckers at the Cove", "giver": "maren", "level": 41, "min": 40, "after": ["crabs_in_the_nets"], "chain": "The Wreckers",
		"offer": "Three ships run onto the rocks at the cove since the spring. Three. No captain I know is that bad. Somebody's putting out false lights, and somebody's picking the wrecks clean — puglins, from the south isles, with more teeth than sense. Ten of them. Make the cove unwelcoming.",
		"goal": "Kill 10 Puglin Wreckers at Wrecker's Cove, south along the shore.", "progress": "They're still out there with their lanterns. I can see them from my window.", "done": "That will slow them down. It won't stop them. Nothing stops a puglin but a bigger puglin.",
		"obj": [{"kind": "kill", "mon": "puglin_wrecker", "n": 10}], "xp": 7000, "money": 42000, "rep": 75, "where": "Wrecker's Cove, south along the shore"},
	"lamp_oil": {"title": "Stolen Lamp Oil", "giver": "tobiah", "level": 41, "min": 40, "chain": "The Light",
		"offer": "Forty years I've kept this light, and forty years it's never gone out. Then the wreckers took my oil — rolled the casks down to the cove in the night, bold as brass. They burn it in their false lanterns. My oil. Luring ships onto the rocks with MY oil. Bring it back.",
		"goal": "Take back 6 casks of Lamp Oil from the Puglin Wreckers at the cove.", "progress": "The light's burning low. I'm rationing it, a wick at a time.", "done": "Oh, that's the good stuff, that is. Smell that. I'll have her burning bright by dusk.",
		"obj": [{"kind": "collect", "item": "lamp_oil_cask", "n": 6, "from": ["puglin_wrecker"], "chance": 0.5}], "xp": 7000, "money": 42000, "choice": ["keepers_lantern", "tobiahs_oilskin", "lamplighters_rod"], "rep": 75, "where": "Wrecker's Cove, south along the shore"},
	"driftwood_beacon": {"title": "The Driftwood Beacon", "giver": "tobiah", "level": 42, "min": 40, "after": ["lamp_oil"], "chain": "The Light",
		"offer": "The lamp's a lamp, but on a bad night you need a beacon too — a fire on the point that you can see from the far side of a gale. Dry driftwood burns best, and the beaches east of here are covered in it. The pale stuff, mind. Not the green.",
		"goal": "Gather 6 pieces of Dry Driftwood from the beaches east of the lighthouse.", "progress": "Dry, I said. Pale and dry.", "done": "That'll catch. Tonight, every ship between here and the south isles will know where the rocks are.",
		"obj": [{"kind": "gather", "item": "dry_driftwood", "n": 6}], "xp": 7300, "money": 43800, "rep": 75, "where": "the beaches below the lighthouse"},
	"the_drowned_crew": {"title": "The Drowned Crew", "giver": "ione", "level": 42, "min": 41, "chain": "The Drowned",
		"offer": "The Merrow went down in the first storm of the year with all hands. Now her crew walk up out of the water every night and stand on the beach looking at the town. They don't come closer. That's worse, somehow. Ten of them, please. Gently, if you can. They were ours.",
		"goal": "Lay 10 Drowned Sailors to rest at the Wreck of the Merrow, on the southern shore.", "progress": "The Ember keeps them. We only have to send them home.", "done": "Thank you. I'll ring the bell for each of them tonight. Someone should.",
		"obj": [{"kind": "kill", "mon": "drowned_sailor", "n": 10}], "xp": 7300, "money": 43800, "rep": 75, "where": "the Wreck of the Merrow, on the southern shore"},
	"names_on_the_water": {"title": "Names on the Water", "giver": "ione", "level": 43, "min": 41, "after": ["the_drowned_crew"], "chain": "The Drowned",
		"offer": "Sailors wear a locket with a name in it, so the sea knows who to give back. If you bring me the lockets, I can write to their families. Six would be a start. It's the waiting that does the damage, for the ones at home.",
		"goal": "Bring Sister Ione 6 Drowned Lockets from the Drowned Sailors.", "progress": "Any names?", "done": "Hollis. Brand. Sefa. Old Mattock. Ennis. And — oh. This one's Maren's brother. I'll tell her myself. Give me a moment.",
		"obj": [{"kind": "collect", "item": "drowned_locket", "n": 6, "from": ["drowned_sailor"], "chance": 0.5}], "xp": 7650, "money": 45900, "choice": ["merrows_bell", "ioness_prayer_shawl", "saltstone_signet"], "rep": 75, "where": "the Wreck of the Merrow"},
	"serpents_ashore": {"title": "Serpents Ashore", "giver": "maren", "level": 43, "min": 41, "chain": "The Deep",
		"offer": "The serpents never came ashore. Never, in my lifetime or my mother's. Now they lie out on the warm stones by the north shore like cats. Something's driving them out of the deep water — and until we know what, I want them off my beach. Eight.",
		"goal": "Kill 8 Sea Serpents basking on the northern shore.", "progress": "They bask in the afternoons. You'll find them.", "done": "Eight. And every one of them fled something, Ione says. Something in the deep water. I don't like any of this.",
		"obj": [{"kind": "kill", "mon": "sea_serpent", "n": 8}], "xp": 7650, "money": 45900, "rep": 75, "where": "the northern shore, past the lighthouse road"},
	"tidecallers": {"title": "The Tidecallers", "giver": "ione", "level": 44, "min": 42, "after": ["serpents_ashore"], "chain": "The Deep",
		"offer": "The serpents are running from the tidecallers — spirits of the sea itself, walking on legs of water. They don't belong on land any more than the serpents do. Somebody called them up. Put six of them back in the sea, and bring me anything you find.",
		"goal": "Destroy 6 Tidecallers among the rocks on the north-east shore.", "progress": "They're made of water. Hit them anyway.", "done": "Salt and cold, and this — a scrap of an admiral's braid, tangled in the last one. Admiral Vesk. The Hold. It's all coming from the Hold.",
		"obj": [{"kind": "kill", "mon": "tidecaller", "n": 6}], "xp": 8000, "money": 48000, "choice": ["tidecallers_mantle", "brinewarden_helm", "coral_band"], "rep": 75, "where": "the rocks on the north-east shore"},
	"old_snapjaw": {"title": "Old Snapjaw", "giver": "cask", "level": 44, "min": 42, "group": true,
		"offer": "There's a crab out on the flats older than this town. Snapjaw, the boys call him. He took my brother's boat in half with one claw, thirty years ago. My brother's fine. The boat isn't. He's come ashore with the others and I want him in my pot. Bring friends.",
		"goal": "Kill Old Snapjaw, the great crab, on the rocks below the lighthouse. (Group)", "progress": "Big as a cart. You can't miss him.", "done": "You got him! My brother's going to cry. Look — a shell like that, you could make armour of it. Take this.",
		"obj": [{"kind": "kill", "mon": "snapjaw", "n": 1}], "xp": 8000, "money": 48000, "items": ["snapjaw_shell_buckler"], "rep": 150, "where": "the rocks below the lighthouse"},
	"gutbag": {"title": "Gutbag, the Wrecker King", "giver": "maren", "level": 45, "min": 43, "after": ["wreckers_cove"], "chain": "The Wreckers", "group": true,
		"offer": "The puglins have a king. Of course they do. Gutbag. He sits in the wreck of the Gull's Pride with a crown made from a ship's bell and gives orders. Cut the head off and the rest will go home. Take a friend. Take two.",
		"goal": "Kill Gutbag, the Wrecker King, at the back of Wrecker's Cove. (Group)", "progress": "Is he still wearing my bell?", "done": "He was wearing the bell? It's the Gull's Pride's bell. We'll hang it back on the pier. Here — you've earned the harbour's thanks, and a little of its money.",
		"obj": [{"kind": "kill", "mon": "gutbag", "n": 1}], "xp": 8400, "money": 50400, "choice": ["wrecker_kings_cleaver", "gutbags_crown_bell", "harbor_watch_girdle"], "rep": 150, "where": "Wrecker's Cove, in the wreck of the Gull's Pride"},
	"into_the_hold": {"title": "Into the Drowned Hold", "giver": "ione", "level": 46, "min": 43, "after": ["tidecallers"], "chain": "The Deep", "group": true, "dungeon": "drowned_hold",
		"offer": "Vesk. Admiral Vesk. He sank with his flagship in the sea cave under the lighthouse, a hundred years ago, and the old people say he never stopped giving orders. Now the sea is doing what he tells it. The Drowned Hold is under Tobiah's light. Go down with friends, and end his command.",
		"goal": "In the Drowned Hold, defeat Bosun Grell, the Brine Mother and Admiral Vesk. (Dungeon: group of 2 or more)", "progress": "Is it done? The tide feels different today.", "done": "The tide turned an hour ago, the right way, for the first time in months. Tobiah felt it in his knees. The whole town felt it. Thank you.",
		"obj": [{"kind": "kill", "mon": "bosun_grell", "n": 1}, {"kind": "kill", "mon": "brine_mother", "n": 1}, {"kind": "kill", "mon": "admiral_vesk", "n": 1}], "xp": 21850, "money": 131100, "choice": ["vesks_cutlass_q", "admirals_greatcoat", "tidebound_signet"], "rep": 400, "where": "the sea cave beneath the lighthouse"},
	"salt_to_ember": {"title": "Salt to Ember", "giver": "maren", "ender": "brunna", "level": 46, "min": 45, "after": ["crabs_in_the_nets"], "chain": "The Salt Road", "provide": ["marens_cargo_note"],
		"offer": "The boats are out again. The first cargo of the year goes up the Cinder Stair to Forgehold — salt fish for the smiths, and a note from me to the Forgemaster. Brunna and I go back. Tell her the harbour's open, and ask her why her rivets stopped coming. I suspect we both had a bad year.",
		"goal": "Take Maren's cargo note up the Cinder Stair to Forgemaster Brunna in Forgehold.", "done": "Salt fish! Oh, the smiths will weep. And a note from Maren — she writes like a gull shouts. Sit. Warm yourself. It's been a bad year up here too.",
		"obj": [{"kind": "talk", "npc": "brunna", "take": "marens_cargo_note"}], "xp": 5250, "money": 31500, "rep": 75},
	"cinder_crawlers": {"title": "Cinder Crawlers", "giver": "brunna", "level": 46, "min": 45, "chain": "Forgehold",
		"offer": "The worms come up out of the lava lake and eat the slag heaps — which I wouldn't mind, but they don't stop at the slag. Last week they ate a cart. Twelve of them, and the haulers can go back to work.",
		"goal": "Kill 12 Magma Worms on the shores of the Lava Lake, west of Forgehold.", "progress": "They leave a glowing trail. Follow it.", "done": "Twelve. The haulers owe you a drink, and they're the sort who pay their debts. Mind your boots — the lake shore's hot.",
		"obj": [{"kind": "kill", "mon": "magma_worm", "n": 12}], "xp": 8750, "money": 52500, "rep": 75, "where": "the shores of the Lava Lake, west"},
	"fiends_in_the_forge": {"title": "Fiends in the Forge", "giver": "brunna", "level": 47, "min": 45, "after": ["cinder_crawlers"], "chain": "Forgehold",
		"offer": "The old Ashworks — the first forge, before Forgehold — is full of imps. Fiends, the smiths say, because 'imps' makes them sound small, and they aren't. Somebody opened a door in the old furnace that should have stayed shut. Ten of them.",
		"goal": "Kill 10 Cinder Fiends in the Ashworks, north-west of the Lava Lake.", "progress": "They throw fire. Duck.", "done": "Ten. I sent a lad to look at the furnace door. He came back white. Something bigger is coming through behind them.",
		"obj": [{"kind": "kill", "mon": "cinder_fiend", "n": 10}], "xp": 9150, "money": 54900, "rep": 75, "where": "the Ashworks, north-west of the Lava Lake"},
	"slag_and_shards": {"title": "Slag and Shards", "giver": "dain", "level": 47, "min": 45,
		"offer": "The obsidian guardians — walking glass, near enough — are the finest source of edge-stone in the world, and they don't like to share. Eight shards and I can put a proper edge on every blade in Forgehold. You'll get the first one.",
		"goal": "Bring Quartermaster Dain 8 Obsidian Shards from the Obsidian Guardians on the Black Glass Fields.", "progress": "Obsidian cuts clean. Mind your fingers.", "done": "Beautiful. Look at that edge. Here — the first blade off the wheel is yours, as promised.",
		"obj": [{"kind": "collect", "item": "obsidian_shard_q", "n": 8, "from": ["obsidian_guard"], "chance": 0.55}], "xp": 9150, "money": 54900, "choice": ["glassedge_blade", "obsidian_focus", "blackglass_legguards"], "rep": 75, "where": "the Black Glass Fields, north of the lake"},
	"the_smelter": {"title": "The Smelter", "giver": "brunna", "level": 48, "min": 46, "after": ["fiends_in_the_forge"], "chain": "Forgehold", "group": true,
		"offer": "It's come through. The lad was right. The smiths call it the Smelter: a thing of iron and fire standing in the old furnace door, pulling metal out of the ground like thread. Kill it before it pulls the mountain down on our heads. Take friends.",
		"goal": "Destroy the Smelter at the Ashworks furnace. (Group)", "progress": "It's still standing in the door. I can see the glow from the wall.", "done": "It's out. The glow's gone. The furnace is just a furnace again. You don't know how good that sounds to a smith.",
		"obj": [{"kind": "kill", "mon": "the_smelter", "n": 1}], "xp": 9500, "money": 57000, "choice": ["smelters_gauntlets", "furnaceheart_band", "ashworks_cloak"], "rep": 150, "where": "the Ashworks furnace, north-west"},
	"drake_hunt": {"title": "Drake Hunt", "giver": "ketch", "level": 48, "min": 46, "chain": "The Roost",
		"offer": "You look like someone who's hunted. Good. The drakes are nesting on the Roost this year, early and in numbers, and they're taking the goats. Then they'll take the goatherds. Eight of them, before they get used to the taste.",
		"goal": "Kill 8 Ember Drakes at the Roost, east of Forgehold.", "progress": "They fly low when they hunt. That's your moment.", "done": "Eight! Not bad for a lowlander. Not bad at all. The goatherds can bring the flocks back down.",
		"obj": [{"kind": "kill", "mon": "ember_drake", "n": 8}], "xp": 9500, "money": 57000, "rep": 75, "where": "the Roost, east of Forgehold"},
	"drake_scales": {"title": "Scale by Scale", "giver": "ketch", "level": 49, "min": 47, "after": ["drake_hunt"], "chain": "The Roost",
		"offer": "Drake scale, done right, stops an arrow and shrugs off fire. Done wrong, it's a very expensive rattle. I need perfect scales — the ones from the shoulder, unscorched. Six. Most drakes have one. Some don't. You'll see.",
		"goal": "Bring Ketch 6 Perfect Drake Scales from Ember Drakes.", "progress": "Unscorched, mind.", "done": "Now that's scale. I'll have a coat out of this by the end of the week. There's a piece in it for you.",
		"obj": [{"kind": "collect", "item": "perfect_drake_scale", "n": 6, "from": ["ember_drake"], "chance": 0.5}], "xp": 9900, "money": 59400, "choice": ["drakescale_vest", "drakehunters_boots", "roostkeepers_charm"], "rep": 75, "where": "the Roost, east of Forgehold"},
	"pyreclaw": {"title": "Pyreclaw", "giver": "ketch", "level": 50, "min": 48, "after": ["drake_scales"], "chain": "The Roost", "group": true,
		"offer": "There's a big one. There's always a big one. Pyreclaw — older than Forgehold, and she's the reason the others nest here. She spits burning stone. Bring a healer and don't stand in the same place twice.",
		"goal": "Kill Pyreclaw, the great drake of the Roost. (Group)", "progress": "Burning stone. I'm not exaggerating.", "done": "Pyreclaw. I've been hunting her for eleven years. Eleven. Here — take my bow. No, take it. I'm done. I'll hang it over the fire and tell this story until I die.",
		"obj": [{"kind": "kill", "mon": "pyreclaw", "n": 1}], "xp": 10300, "money": 61800, "items": ["ketchs_longbow_charm"], "rep": 150, "where": "the top of the Roost, east"},
	"ravagers": {"title": "The Cinderhide", "giver": "ysolde", "level": 49, "min": 47, "chain": "The Wardens",
		"offer": "The Cinderhide are lycans that have learned to live in the burning wood — their fur's half ash. They used to keep to the wood. Now they raid the road from the coast and burn the carts. Ten of them. The Wardens will do the rest.",
		"goal": "Kill 10 Cinderhide Ravagers in the Charred Wood, south of Forgehold.", "progress": "Their howl carries. You'll hear them before you see them.", "done": "Ten. The road's quieter. Maren's cargo got through, you'll be glad to hear — every fish of it.",
		"obj": [{"kind": "kill", "mon": "cinderhide", "n": 10}], "xp": 9900, "money": 59400, "rep": 75, "where": "the Charred Wood, south of Forgehold"},
	"slag_elementals": {"title": "Living Slag", "giver": "ysolde", "level": 50, "min": 48, "after": ["ravagers"], "chain": "The Wardens",
		"offer": "The slag heaps are getting up and walking. I've studied the lava lake for twenty years, and I've never seen slag walk. The Smelter was pulling on the mountain — and something deeper is still pulling. Break eight of them up so I can study the pieces.",
		"goal": "Destroy 8 Slag Elementals in the Slag Fields, west.", "progress": "Bring me a piece if you can. A cold one.", "done": "Still warm. Still humming. Whatever is pulling on the mountain, it's under the Deep. Tharn's old forge. I was afraid of that.",
		"obj": [{"kind": "kill", "mon": "slag_elemental", "n": 8}], "xp": 10300, "money": 61800, "choice": ["wardens_emberstave", "slagforged_pauldrons", "cinderweave_wraps"], "rep": 75, "where": "the Slag Fields, west of the lake"},
	"tharns_forge": {"title": "Tharn's Forge", "giver": "brunna", "ender": "ysolde", "level": 51, "min": 48, "after": ["the_smelter"], "chain": "Forgehold",
		"offer": "Ysolde's been muttering about Tharn's forge for a week. Tharn was Forgemaster before me — before my mother, even. He went down into the Deep to build a forge in the mountain's heart and never came back up. Ask her what she thinks is down there. I can't bring myself to.",
		"goal": "Ask Warden Ysolde what lies in the Molten Deep.", "done": "Tharn's down there, Brunna knows it, and he's not alone. He found something in the mountain's heart — a thing of fire, very old, called Azhul. It made him its smith. They are forging something in the Deep, and the whole mountain feels it.",
		"obj": [{"kind": "talk", "npc": "ysolde"}], "xp": 5350, "money": 32100, "rep": 75},
	"into_the_deep": {"title": "Into the Molten Deep", "giver": "ysolde", "level": 52, "min": 49, "after": ["tharns_forge"], "chain": "Forgehold", "group": true, "dungeon": "molten_deep",
		"offer": "The Molten Deep is under the Black Glass Fields. Tharn's in there, and Azhul, and whatever they're making. Go down with friends, put Tharn to rest, and put the fire back to sleep. Brunna will want to know how he died. Tell her he died a smith.",
		"goal": "In the Molten Deep, defeat Slagjaw, Forgemaster Tharn and Pyrelord Azhul. (Dungeon: group of 2 or more)", "progress": "The mountain is still humming. Can you feel it?", "done": "The humming's stopped. Brunna's on the wall with her eyes closed, listening to nothing at all. She'll thank you herself — she just needs a while.",
		"obj": [{"kind": "kill", "mon": "slagjaw", "n": 1}, {"kind": "kill", "mon": "forgemaster_tharn", "n": 1}, {"kind": "kill", "mon": "pyrelord_azhul", "n": 1}], "xp": 27850, "money": 167100, "choice": ["heart_of_azhul_q", "tharns_last_work", "emberheart_signet"], "rep": 400, "where": "the Molten Deep, under the Black Glass Fields"},
	"ember_to_frost": {"title": "The Frostgate", "giver": "brunna", "ender": "aldric", "level": 52, "min": 51, "after": ["cinder_crawlers"], "chain": "The Salt Road", "provide": ["brunnas_letter"],
		"offer": "Wintermere wants iron and we've iron to spare now, thanks to you. Take this letter through the Frostgate to Aldric — the Huntmaster, he runs the place, whatever he says. Dress warm. You've been living next to a lava lake; the Reach will come as a shock.",
		"goal": "Take Brunna's letter west through the Frostgate to Huntmaster Aldric in Wintermere.", "done": "Iron! Brunna, you beauty. Come in, come in, stand by the fire, you're blue. How are you blue already? You've been here five minutes.",
		"obj": [{"kind": "talk", "npc": "aldric", "take": "brunnas_letter"}], "xp": 6700, "money": 40200, "rep": 75},
	"wolves_at_the_gate": {"title": "Wolves at the Gate", "giver": "aldric", "level": 52, "min": 51, "chain": "Wintermere",
		"offer": "The frost wolves come down from the peaks every winter. Every winter we drive them back up. This winter they didn't go back up. Twelve, in the Wolfrun, and the woodcutters can go back to cutting wood.",
		"goal": "Kill 12 Frost Wolves in the Wolfrun, south of Wintermere.", "progress": "White on white. Watch for the eyes.", "done": "Twelve. That's a start and a good one. Warm your hands — you've earned the fire.",
		"obj": [{"kind": "kill", "mon": "frost_wolf", "n": 12}], "xp": 11150, "money": 66900, "rep": 75, "where": "the Wolfrun, south of Wintermere"},
	"bear_necessities": {"title": "Whitepelt", "giver": "tove", "level": 53, "min": 51,
		"offer": "It's going to be a long winter. It's always a long winter, but this one's longer. I need pelts — thick ones, from the snow bears by the frozen lake. Six. Enough to line every door in Wintermere.",
		"goal": "Bring Tove 6 Thick White Pelts from Snow Bears.", "progress": "Thick ones. The thin ones just make you cold and sad.", "done": "Six! Oh, these are lovely. Every door in town, and a little left over. I made you something.",
		"obj": [{"kind": "collect", "item": "thick_white_pelt", "n": 6, "from": ["snow_bear"], "chance": 0.55}], "xp": 11550, "money": 69300, "choice": ["whitepelt_hood_cloak", "tovess_mittens", "fur_lined_boots"], "rep": 75, "where": "around the frozen lake"},
	"rams_for_the_winter": {"title": "Rams for the Winter", "giver": "tove", "level": 53, "min": 51,
		"offer": "Horns make the best cups, the best buttons and the best horns. Wintermere's running short of all three. The rams on the east slopes won't bother you unless you bother them. Bother eight of them.",
		"goal": "Bring Tove 8 Ram Horns from the Mountain Rams on the eastern slopes.", "progress": "They don't fight back much. They do run, though.", "done": "Cups, buttons and horns. Wintermere thanks you. The rams don't.",
		"obj": [{"kind": "collect", "item": "ram_horn", "n": 8, "from": ["mountain_ram"], "chance": 0.7}], "xp": 11550, "money": 69300, "rep": 75, "where": "the eastern slopes"},
	"the_rimeborn": {"title": "The Rimeborn", "giver": "sigrun", "level": 53, "min": 52, "chain": "The Frozen King",
		"offer": "The old kings of the Reach are buried at the Barrows with their warriors around them, and they've stood up. All of them. Walking ice with swords in their hands. Ten, please, and quickly. They're heading this way, a step a day.",
		"goal": "Destroy 10 Rimeborn at the Barrows, west of Wintermere.", "progress": "A step a day, but every day.", "done": "Ten fewer. The rest are still coming. Something woke them — something that wears a crown.",
		"obj": [{"kind": "kill", "mon": "rimeborn", "n": 10}], "xp": 11550, "money": 69300, "rep": 75, "where": "the Barrows, west of Wintermere"},
	"ice_golems": {"title": "The Walking Ice", "giver": "eir", "level": 54, "min": 52, "after": ["the_rimeborn"], "chain": "The Frozen King",
		"offer": "The ice on the lake has stood up and walked off. I'm a runescribe; I know what it takes to make ice walk, and it takes a lot. Eight of them, please, and I'll read what's written in the pieces.",
		"goal": "Destroy 8 Ice Golems at the Frozen Lake.", "progress": "The runes are on their chests. Aim there.", "done": "Frost runes, very old. 'Serve the King.' Just that, over and over. Sigrun won't like that.",
		"obj": [{"kind": "kill", "mon": "ice_golem", "n": 8}], "xp": 12000, "money": 72000, "rep": 75, "where": "the Frozen Lake"},
	"runes_in_the_ice": {"title": "Runes in the Ice", "giver": "eir", "level": 54, "min": 52, "after": ["ice_golems"], "chain": "The Frozen King",
		"offer": "Whoever woke the Rimeborn used the standing stones at the Barrows to do it. The runes will have cracked off the stones — they do that, when they're overworked. Six shards and I can tell you who.",
		"goal": "Gather 6 Rune Shards from the standing stones at the Barrows.", "progress": "They glow a little. Blue.", "done": "Hrimgar. The Frozen King. He's calling them from the Frostspire. Of course he is. It's always a king.",
		"obj": [{"kind": "gather", "item": "rune_shard", "n": 6}], "xp": 12000, "money": 72000, "choice": ["runescribes_circlet", "iceward_girdle", "barrow_kings_ring"], "rep": 75, "where": "the standing stones at the Barrows, west"},
	"snowmane": {"title": "The Snowmane", "giver": "aldric", "level": 54, "min": 53, "after": ["wolves_at_the_gate"], "chain": "Wintermere",
		"offer": "The Snowmane are lycans who came over the peaks last autumn, and they've been in the northern pass ever since, eating anything that walks the road. The road north goes to the Scar, and the Watch needs that road. Ten of them.",
		"goal": "Kill 10 Snowmane Lycans at their camp in the northern pass.", "progress": "They hunt in threes. Pick off the third.", "done": "Ten. The pass is open. Corvin's riders will get through now — he's been cut off at the Watch for a month.",
		"obj": [{"kind": "kill", "mon": "snowmane", "n": 10}], "xp": 12000, "money": 72000, "rep": 75, "where": "the northern pass"},
	"rime_witches": {"title": "The Rime Witches", "giver": "sigrun", "level": 55, "min": 53, "after": ["runes_in_the_ice"], "chain": "The Frozen King",
		"offer": "The rime witches serve the Frozen King. They freeze the breath in your chest, if you let them. Eight, at the foot of the Frostspire. The Ember will keep you warm. So will a good hat.",
		"goal": "Kill 8 Rime Witches at the Frostspire's foot.", "progress": "They're at the foot of the spire. Their breath is cold enough to see.", "done": "Eight. And Skadi — the eldest of them — wasn't among them. She's inside, with the King.",
		"obj": [{"kind": "kill", "mon": "rime_witch", "n": 8}], "xp": 12450, "money": 74700, "choice": ["sigruns_ember_charm", "frostbinder_robe", "wintersteel_legplates"], "rep": 75, "where": "the foot of the Frostspire, west"},
	"old_whitefang": {"title": "Old Whitefang", "giver": "aldric", "level": 55, "min": 53, "after": ["snowmane"], "chain": "Wintermere", "group": true,
		"offer": "There's a wolf in the Wolfrun as big as a pony, and white as the snow, and he's leading the pack down on us. Old Whitefang. My grandfather hunted him. My father hunted him. I'd like to be the one who finishes it, but my knees say you are. Bring friends.",
		"goal": "Kill Old Whitefang, the pack leader of the Wolfrun. (Group)", "progress": "Big as a pony. I said that already. I'll say it again.", "done": "Whitefang. Three generations. My grandfather would have bought you a drink. My father would have bought you a horse. I'll give you this — it was his.",
		"obj": [{"kind": "kill", "mon": "old_whitefang", "n": 1}], "xp": 12450, "money": 74700, "items": ["whitefang_mantle"], "rep": 150, "where": "the deep Wolfrun, south"},
	"into_the_frostspire": {"title": "Into the Frostspire", "giver": "sigrun", "level": 57, "min": 54, "after": ["rime_witches"], "chain": "The Frozen King", "group": true, "dungeon": "frostspire",
		"offer": "Hrimgar was the last king of the Reach, and a hard one. When Vaal's Scar opened, he went into the Frostspire to wait for the end of the world — and something from the Scar found him there. Now he calls the dead. Go into the Halls with friends and take his crown off.",
		"goal": "In Frostspire Halls, defeat Ursoth the Frostmaw, Rime Witch Skadi and Hrimgar, the Frozen King. (Dungeon: group of 2 or more)", "progress": "The Barrows are still walking.", "done": "The Barrows are still. Every one of the Rimeborn lay down at the same moment. Eir says it's like a held breath being let out. Thank you, from all of us — and from them.",
		"obj": [{"kind": "kill", "mon": "ursoth", "n": 1}, {"kind": "kill", "mon": "skadi", "n": 1}, {"kind": "kill", "mon": "hrimgar", "n": 1}], "xp": 33350, "money": 200100, "choice": ["crown_of_hrimgar_q", "frostspire_greatstaff", "winterheart_pendant"], "rep": 400, "where": "Frostspire Halls, in the western spire"},
	"the_last_road": {"title": "The Last Road", "giver": "aldric", "ender": "corvin", "level": 56, "min": 55, "after": ["snowmane"], "chain": "The Salt Road", "provide": ["aldrics_dispatch"],
		"offer": "Corvin's riders got through. The Watch is holding, just, at the edge of the Scar. He's asked for anyone who can fight. That's you. Take this north on the Last Road. I'll say it now so I've said it: be careful. Nobody comes back from the Scar the same.",
		"goal": "Take Aldric's dispatch north along the Last Road to High Marshal Corvin at the Last Watch.", "done": "Aldric sent you? Then you're the one who opened the pass. Welcome to the Last Watch. We're the last of everything up here. Last fire, last wall, last light before the Scar.",
		"obj": [{"kind": "talk", "npc": "corvin", "take": "aldrics_dispatch"}], "xp": 7750, "money": 46500, "rep": 75},
	"void_imps": {"title": "Voidlings", "giver": "corvin", "level": 57, "min": 56, "chain": "The Last Watch",
		"offer": "The Scar leaks. Every night something small and hungry crawls out of it and heads for our fires. Void imps. They're not dangerous alone. They're never alone. Twelve, in the western Wastes.",
		"goal": "Kill 12 Void Imps in the Wastes, west of the Watch.", "progress": "They burn purple. You'll see them.", "done": "Twelve. My sentries will sleep tonight, which is more than they did last night.",
		"obj": [{"kind": "kill", "mon": "void_imp", "n": 12}], "xp": 13350, "money": 80100, "rep": 75, "where": "the Wastes, west of the Watch"},
	"soul_wraiths": {"title": "The Lost", "giver": "amara", "level": 57, "min": 56, "chain": "The Lost",
		"offer": "Every soul Vaal takes, he keeps. The ones he doesn't need walk the Hollow Field, looking for the way home. Send them on. Ten. I'll pray for the rest, and you'll hear me doing it all night, I'm afraid.",
		"goal": "Put 10 Soul Wraiths to rest in the Hollow Field, north-west.", "progress": "They don't know they're dead. Be kind, but be quick.", "done": "Ten souls gone home. The light will know them. Thank you, friend.",
		"obj": [{"kind": "kill", "mon": "soul_wraith", "n": 10}], "xp": 13350, "money": 80100, "rep": 75, "where": "the Hollow Field, north-west"},
	"voidforged": {"title": "The Voidforged", "giver": "corvin", "level": 58, "min": 56, "after": ["void_imps"], "chain": "The Last Watch",
		"offer": "Vaal's knights — Voidforged, the scouts call them — hold the Broken Road between us and the Sanctum. Knights in armour that was never made by any smith. Eight of them. Then the road is ours, and we can see what he's building.",
		"goal": "Kill 8 Voidforged Knights on the Broken Road, north of the Watch.", "progress": "They don't bleed. Hit them anyway.", "done": "Eight. The scouts are on the Broken Road now. They can see the Sanctum Gate from the top of it. They say it's open. They say it's breathing.",
		"obj": [{"kind": "kill", "mon": "voidforged", "n": 8}], "xp": 13800, "money": 82800, "choice": ["watchguard_plate", "voidwarded_robe", "last_watch_signet"], "rep": 75, "where": "the Broken Road, north of the Watch"},
	"void_ichor": {"title": "Ichor", "giver": "amara", "level": 58, "min": 56, "after": ["soul_wraiths"], "chain": "The Lost",
		"offer": "What runs in the veins of Vaal's creatures is the same stuff the Scar is made of. If I have enough of it, I can see through it — see what's on the other side of the Gate. Eight vials. Don't drink any. I have to say that. Somebody always does.",
		"goal": "Bring Seer Amara 8 vials of Void Ichor from Void Imps and Soul Wraiths.", "progress": "Don't drink any.", "done": "Eight. Now — hold still, and watch the bowl with me. There. That's the Sanctum. And that — that's Vaal, and he's waking.",
		"obj": [{"kind": "collect", "item": "void_ichor_q", "n": 8, "from": ["void_imp", "soul_wraith"], "chance": 0.5}], "xp": 13800, "money": 82800, "rep": 75, "where": "the Wastes and the Hollow Field"},
	"the_chosen": {"title": "Vaal's Chosen", "giver": "corvin", "level": 59, "min": 57, "after": ["voidforged"], "chain": "The Last Watch",
		"offer": "The Chosen came over the Scar last night, a whole war band of them, and dug in on the east rim. They're lycans that took Vaal's mark. They'll hit us tomorrow unless we hit them tonight. Ten, and they'll think better of it.",
		"goal": "Kill 10 of Vaal's Chosen at their camp on the Scar's edge, east.", "progress": "They're dug in on the east rim.", "done": "Ten. They pulled back over the rim an hour ago. We have a day or two. That will be enough, I think.",
		"obj": [{"kind": "kill", "mon": "vaals_chosen", "n": 10}], "xp": 14300, "money": 85800, "rep": 75, "where": "the east rim of the Scar"},
	"void_horrors": {"title": "Void Horrors", "giver": "amara", "level": 59, "min": 57, "after": ["void_ichor"], "chain": "The Lost",
		"offer": "The Void Pool is where the Scar is thinnest. Things come up out of it — the horrors — and they unmake the ground they walk on. Six. Then I can close the pool, a little, for a while.",
		"goal": "Destroy 6 Void Horrors at the Void Pool, north-east.", "progress": "They burst when they die. Stand back.", "done": "Six. The pool's quieter. I closed it — a little. For a while. It's the best anyone can do, this close to him.",
		"obj": [{"kind": "kill", "mon": "void_horror", "n": 6}], "xp": 14300, "money": 85800, "choice": ["seers_voidglass", "horrorbane_gauntlets", "unmade_cloak"], "rep": 75, "where": "the Void Pool, north-east"},
	"voidcallers": {"title": "The Voidcallers", "giver": "corvin", "level": 59, "min": 57, "after": ["the_chosen"], "chain": "The Last Watch",
		"offer": "The cult. It's always a cult. They stand in a ring by the Gate and sing, and Vaal listens. Eight of them. Stop the singing.",
		"goal": "Kill 8 Voidcallers at the Cult Ring, north-west of the Gate.", "progress": "You'll hear them. Everyone can hear them.", "done": "The singing's stopped. It's the first quiet night at the Watch since I came here. Sleep, if you can.",
		"obj": [{"kind": "kill", "mon": "voidcaller", "n": 8}], "xp": 14300, "money": 85800, "rep": 75, "where": "the Cult Ring, north-west of the Gate"},
	"doomherald": {"title": "The Doomherald", "giver": "corvin", "level": 60, "min": 58, "after": ["voidcallers"], "chain": "The Last Watch", "group": true,
		"offer": "Kess. Vaal's herald, his voice in the world. He was the one who opened the Scar, the old stories say, and he's been waiting ever since for his master to wake. He stands at the Broken Crown, north-east, and he's never alone. Take the best people you know.",
		"goal": "Kill Doomherald Kess at the Broken Crown, north-east. (Group)", "progress": "He's still up there. I can feel him watching the Watch.", "done": "Kess is dead. I don't know what that means for Vaal — nobody does — but I know the Watch has never been so glad of anything. Stand with me at the fire tonight. You've earned the warm side.",
		"obj": [{"kind": "kill", "mon": "doomherald_kess", "n": 1}], "xp": 22150, "money": 132900, "choice": ["heralds_bane", "kesss_voidmantle", "crown_breaker_band"], "rep": 150, "where": "the Broken Crown, north-east"},
	"the_gate_breathes": {"title": "The Gate Breathes", "giver": "amara", "level": 60, "min": 58, "after": ["void_horrors"], "chain": "The Lost",
		"offer": "I've seen it in the bowl. Now I need someone to see it with their eyes. Go to the Gate at the top of the Broken Road — don't go through, just look — and come back and tell me what's there. Take the Ember with you.",
		"goal": "Go to the Sanctum Gate at the head of the Broken Road and look through it.", "progress": "Did you see it?", "done": "You saw him. Vaal. Asleep, but not deeply. When he wakes, the Sanctum wakes with him, and then everything. Rest now. Take this key — the Keeper at the Gate will know it. When it's time, it will take ten of you to go through.",
		"obj": [{"kind": "explore", "at": [0, -76], "r": 10.0, "name": "the Sanctum Gate"}], "xp": 11800, "money": 70800, "items": ["sanctum_key"], "rep": 75},
}

## how much experience a quest gives at your level (WoW: much less once it's grey to you)
static func xp_for(id: String, level: int) -> int:
	var q: Dictionary = LIST[id]
	# the numbers in the quest text are the document's; our experience curve wants about four times that
	var x := int(q.get("xp", 0)) * 4

	var d := level - int(q.get("level", 1))
	if d >= 5: return int(x * 0.2)
	if d >= 3: return int(x * 0.6)
	return x

static func objective_text(o: Dictionary, have: int) -> String:
	match o["kind"]:
		"talk": return "Speak to %s" % Npcs.LIST.get(o["npc"], {}).get("name", o["npc"])
		"kill": return "%s slain: %d/%d" % [_mon_name(o["mon"]), mini(have, o["n"]), o["n"]]
		"collect", "gather": return "%s: %d/%d" % [Items.LIST.get(o["item"], {}).get("name", o["item"]), mini(have, o["n"]), o["n"]]
		"explore": return "Find %s%s" % [o.get("name", "the place"), " (done)" if have >= 1 else ""]
		"daily": return "Days fed: %d/%d" % [mini(have, o["n"]), o["n"]]

	return "?"

static func _mon_name(k: String) -> String:
	if k == "restless_bones": return "Restless Bones"
	var d: Dictionary = Monster.KINDS.get(k, {})
	var names: Array = d.get("names", [k])
	return names[0]
